import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

// The icons are generated by their own step now, which means they can be
// forgotten: an APK would then go out carrying the launcher icon of the drawing
// before last. --check is what notices, and 00-MakeAll.sh asks it before building.
void main() {
  late Directory root;

  Future<void> write(String relative, String contents) async {
    final File file = File(p.join(root.path, relative));
    await file.parent.create(recursive: true);
    await file.writeAsString(contents);
  }

  Future<void> touch(String relative, DateTime when) async {
    await File(p.join(root.path, relative)).setLastModified(when);
  }

  setUp(() async {
    root = await Directory.systemTemp.createTemp('easysend-icon-check-');
    await File('02-MakeIcons.sh').copy(p.join(root.path, '02-MakeIcons.sh'));
    await write('tools/make_icon.py', 'drawing');
    await write('assets/icon_small.png', 'master');
    await write('assets/icon_fg.png', 'foreground');
    await write('android/app/src/main/res/mipmap-hdpi/ic_launcher.png', 'icon');
    await write(
      'android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png',
      'fg',
    );

    final DateTime old = DateTime(2026, 8, 17, 10);
    final DateTime later = DateTime(2026, 8, 17, 11);
    for (final String source in [
      'tools/make_icon.py',
      'assets/icon_small.png',
      'assets/icon_fg.png',
    ]) {
      await touch(source, old);
    }
    for (final String generated in [
      'android/app/src/main/res/mipmap-hdpi/ic_launcher.png',
      'android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png',
    ]) {
      await touch(generated, later);
    }
  });

  tearDown(() => root.delete(recursive: true));

  Future<ProcessResult> check() => Process.run('bash', [
    '02-MakeIcons.sh',
    '--check',
  ], workingDirectory: root.path);

  test('generated icons newer than the drawing pass', () async {
    final ProcessResult result = await check();
    expect(result.exitCode, 0, reason: '${result.stdout}${result.stderr}');
  });

  test('a redrawn master is reported, naming the file it beats', () async {
    await touch('tools/make_icon.py', DateTime(2026, 8, 17, 12));

    final ProcessResult result = await check();
    expect(result.exitCode, isNot(0));
    expect(result.stdout, contains('ic_launcher.png'));
    expect(result.stdout, contains('02-MakeIcons.sh'));
  });

  test('no generated icons at all is reported too', () async {
    await Directory(
      p.join(root.path, 'android', 'app', 'src', 'main', 'res'),
    ).delete(recursive: true);

    final ProcessResult result = await check();
    expect(result.exitCode, isNot(0));
    expect(result.stdout, contains('No generated launcher icons'));
  });

  test('the check draws nothing and writes nothing', () async {
    final DateTime before = await File(
      p.join(root.path, 'android/app/src/main/res/mipmap-hdpi/ic_launcher.png'),
    ).lastModified();

    await check();

    expect(
      await File(
        p.join(
          root.path,
          'android/app/src/main/res/mipmap-hdpi/ic_launcher.png',
        ),
      ).lastModified(),
      before,
    );
  });

  // Wired into the full run, or nobody would ever be told.
  test('00-MakeAll.sh asks the check before it builds', () async {
    final String all = await File('00-MakeAll.sh').readAsString();
    final int asked = all.indexOf('02-MakeIcons.sh --check');
    final int builds = all.indexOf('run 10-MakeRelease.sh');
    expect(asked, isNonNegative);
    expect(asked, lessThan(builds));
    // Said again at the end, where it cannot be scrolled past.
    expect(all, contains('Icons may be stale'));
  });
}
