import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

// The launcher resources are generated by their own step now, which means they
// can be forgotten: an APK would then go out carrying the icon of the master
// before last. The step compares the masters with res/ by modification time and
// runs the generator only when it has to; 00-MakeAll.sh runs it before building.
void main() {
  late Directory root;

  Future<void> write(String relative, String contents) async {
    final File file = File(p.join(root.path, relative));
    await file.parent.create(recursive: true);
    await file.writeAsString(contents);
  }

  Future<void> touch(String relative, DateTime when) async {
    await File(p.join(root.path, relative)).setLastModified(when);
  }

  const List<String> generatedIcons = [
    'android/app/src/main/res/mipmap-hdpi/ic_launcher.png',
    'android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png',
  ];

  setUp(() async {
    root = await Directory.systemTemp.createTemp('easysend-icon-step-');
    await File('02-MakeIcons.sh').copy(p.join(root.path, '02-MakeIcons.sh'));
    await write('assets/icon_small.png', 'master');
    await write('assets/icon_fg.png', 'foreground');
    for (final String icon in generatedIcons) {
      await write(icon, 'generated');
    }

    // The generator is recorded rather than run: flutter_launcher_icons needs a
    // Flutter project, which is not what this test is about. python3 is here to
    // prove it is never reached — drawing the masters is a separate, hand-run
    // step and this one must not do it.
    for (final String tool in ['python3', 'dart', 'git']) {
      final File stub = File(p.join(root.path, 'fake-bin', tool));
      await stub.parent.create(recursive: true);
      await stub.writeAsString(r'''#!/usr/bin/env bash
printf '%s\n' "$*" >> "$ICON_FAKE_LOG"
exit 0
''');
      final ProcessResult chmod = await Process.run('chmod', [
        '+x',
        stub.path,
      ]);
      expect(chmod.exitCode, 0);
    }

    final DateTime old = DateTime(2026, 8, 17, 10);
    final DateTime later = DateTime(2026, 8, 17, 11);
    for (final String master in ['assets/icon_small.png', 'assets/icon_fg.png']) {
      await touch(master, old);
    }
    for (final String icon in generatedIcons) {
      await touch(icon, later);
    }
  });

  tearDown(() => root.delete(recursive: true));

  Future<ProcessResult> run() => Process.run(
    'bash',
    ['02-MakeIcons.sh'],
    workingDirectory: root.path,
    environment: {
      ...Platform.environment,
      'PATH': '${p.join(root.path, 'fake-bin')}:${Platform.environment['PATH']}',
      'ICON_FAKE_LOG': p.join(root.path, 'tools.log'),
    },
  );

  Future<List<String>> calls() async {
    final File log = File(p.join(root.path, 'tools.log'));
    if (!await log.exists()) return const [];
    return (await log.readAsLines()).where((String l) => l.isNotEmpty).toList();
  }

  test('resources newer than the masters are left alone', () async {
    final ProcessResult result = await run();
    expect(result.exitCode, 0, reason: '${result.stdout}${result.stderr}');
    expect(result.stdout, contains('nothing to do'));
    expect(await calls(), isEmpty);
  });

  test('a newer master sets the generator going, and only it', () async {
    await touch('assets/icon_small.png', DateTime(2026, 8, 17, 12));

    final ProcessResult result = await run();
    expect(result.exitCode, 0, reason: '${result.stdout}${result.stderr}');
    // Said before the work, naming both sides of the comparison it lost.
    expect(result.stdout, contains('Older than assets/icon_small.png'));
    expect(
      await calls(),
      contains(
        predicate<String>((String c) => c.contains('flutter_launcher_icons')),
      ),
    );
    // The masters are drawn by hand; this step never redraws them.
    expect(
      await calls(),
      isNot(contains(predicate<String>((String c) => c.contains('make_icon')))),
    );
  });

  test('nothing generated at all counts as out of date', () async {
    await Directory(
      p.join(root.path, 'android', 'app', 'src', 'main', 'res'),
    ).delete(recursive: true);

    final ProcessResult result = await run();
    expect(result.exitCode, 0, reason: '${result.stdout}${result.stderr}');
    expect(result.stdout, contains('No generated launcher icons'));
    expect(await calls(), isNotEmpty);
  });

  // Wired into the full run, or a build could still go out with the old icon.
  test('00-MakeAll.sh runs the step before it builds', () async {
    final String all = await File('00-MakeAll.sh').readAsString();
    final int icons = all.indexOf('bash 02-MakeIcons.sh');
    final int builds = all.indexOf('run 10-MakeRelease.sh');
    expect(icons, isNonNegative);
    expect(icons, lessThan(builds));
  });
}
